
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package lexgen;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Multiplicacion = 5;
  public static final int SQLCODE = 272;
  public static final int DECLARE = 154;
  public static final int INTEGER = 270;
  public static final int SIZE = 262;
  public static final int DATABASE = 145;
  public static final int RELATIVE = 240;
  public static final int SOME = 117;
  public static final int MONTH = 307;
  public static final int BOTH = 244;
  public static final int GO = 241;
  public static final int PIVOT = 195;
  public static final int CLOSE = 85;
  public static final int GB = 367;
  public static final int END_EXEC = 337;
  public static final int Coma = 18;
  public static final int PAD = 214;
  public static final int MODULE = 305;
  public static final int USE = 176;
  public static final int DAY = 304;
  public static final int CONSTRAINT = 106;
  public static final int SCROLL_LOCKS = 361;
  public static final int WRITETEXT = 208;
  public static final int BROWSE = 64;
  public static final int CONTINUE = 115;
  public static final int PROCEDURE = 232;
  public static final int Suma = 3;
  public static final int OPENDATASOURCE = 166;
  public static final int WRITE = 338;
  public static final int LEVEL = 290;
  public static final int FETCH = 34;
  public static final int ZONE = 341;
  public static final int CATALOG = 253;
  public static final int INTERSECT = 101;
  public static final int MODULAR = 373;
  public static final int TRUE = 308;
  public static final int DENY = 162;
  public static final int OFF = 155;
  public static final int DEALLOCATE = 151;
  public static final int SECTION = 252;
  public static final int FROM = 53;
  public static final int TEXTSIZE = 132;
  public static final int DUMP = 182;
  public static final int SET = 108;
  public static final int ASC = 230;
  public static final int SQLERROR = 274;
  public static final int DIAGNOSTICS = 326;
  public static final int KEY = 113;
  public static final int TIMEZONE_HOUR = 292;
  public static final int SQLCA = 271;
  public static final int MenorIgual = 13;
  public static final int RESTRICT = 57;
  public static final int KEYSET = 357;
  public static final int FREETEXT = 47;
  public static final int GET = 238;
  public static final int MAXSIZE = 370;
  public static final int OPTION = 178;
  public static final int NUMERIC = 327;
  public static final int ARE = 227;
  public static final int LINENO = 125;
  public static final int DESCRIPTOR = 325;
  public static final int SECURITYAUDIT = 90;
  public static final int NULLIF = 149;
  public static final int POSITION = 220;
  public static final int DECIMAL = 311;
  public static final int SECOND = 250;
  public static final int COUNT = 287;
  public static final int PRECISION = 201;
  public static final int NONE = 321;
  public static final int LAST = 285;
  public static final int DISCONNECT = 329;
  public static final int CURRENT_USER = 139;
  public static final int EXECUTE = 203;
  public static final int SAVE = 84;
  public static final int TRUNCATE = 153;
  public static final int DEFAULT = 157;
  public static final int SESSION_USER = 105;
  public static final int BY = 70;
  public static final int Porcentaje = 11;
  public static final int DEFERRED = 318;
  public static final int EXISTS = 206;
  public static final int ERROR = 29;
  public static final int BIT = 242;
  public static final int HAVING = 71;
  public static final int LANGUAGE = 283;
  public static final int IDENTITY_INSERT = 80;
  public static final int CURRENT_TIME = 133;
  public static final int INDEX = 92;
  public static final int THEN = 135;
  public static final int BIT_LENGTH = 243;
  public static final int AT = 235;
  public static final int EOF = 0;
  public static final int NoIgual = 16;
  public static final int ALLOCATE = 221;
  public static final int AS = 44;
  public static final int EXTRACT = 219;
  public static final int TRIGGER = 150;
  public static final int OPENROWSET = 172;
  public static final int INT = 267;
  public static final int TIMEZONE_MINUTE = 294;
  public static final int BACKUP = 52;
  public static final int VALUES = 181;
  public static final int Menor = 12;
  public static final int NEXT = 316;
  public static final int ANY = 41;
  public static final int Parentesis = 24;
  public static final int KILL = 116;
  public static final int SUBSTRING = 280;
  public static final int PUBLIC = 35;
  public static final int SEMANTICSIMILARITYDETAILSTABLE = 99;
  public static final int FORWARD_ONLY = 355;
  public static final int CASCADED = 247;
  public static final int BREAK = 61;
  public static final int PREPARE = 223;
  public static final int END = 188;
  public static final int ELSE = 185;
  public static final int VIEW = 187;
  public static final int PERCENT = 192;
  public static final int AND = 31;
  public static final int cadena = 9;
  public static final int OPTIMISTIC = 362;
  public static final int NCHAR = 314;
  public static final int RETURN = 60;
  public static final int DBCC = 148;
  public static final int CONTAINS = 109;
  public static final int ROLLBACK = 72;
  public static final int CONNECTION = 277;
  public static final int FOREIGN = 45;
  public static final int ESCAPE = 194;
  public static final int TYPE_WARNING = 363;
  public static final int CURSOR = 142;
  public static final int Numeral = 21;
  public static final int NATURAL = 312;
  public static final int UNPIVOT = 167;
  public static final int CierraParentesis = 28;
  public static final int FILEGROWTH = 372;
  public static final int NONCLUSTERED = 140;
  public static final int IMMEDIATE = 249;
  public static final int RULE = 81;
  public static final int INTO = 104;
  public static final int READONLY = 344;
  public static final int ALL = 218;
  public static final int Llaves = 23;
  public static final int LOAD = 128;
  public static final int TABLESAMPLE = 129;
  public static final int MARK = 354;
  public static final int RECOMPILE = 353;
  public static final int COLUMN = 97;
  public static final int BEGIN = 55;
  public static final int CORRESPONDING = 284;
  public static final int OPENQUERY = 169;
  public static final int OFFSETS = 158;
  public static final int FILENAME = 365;
  public static final int LOWER = 295;
  public static final int SQLWARNING = 278;
  public static final int UNLIMITED = 371;
  public static final int OCTET_LENGTH = 330;
  public static final int Punto = 19;
  public static final int UNIQUE = 164;
  public static final int GRANT = 65;
  public static final int TRY_CONVERT = 156;
  public static final int ROWS = 245;
  public static final int INTERVAL = 273;
  public static final int OPEN = 163;
  public static final int WORK = 336;
  public static final int CURRENT_DATE = 130;
  public static final int TIMESTAMP = 291;
  public static final int ALTER = 36;
  public static final int PRIVILEGES = 229;
  public static final int TOP = 141;
  public static final int REVOKE = 66;
  public static final int FULL = 56;
  public static final int RESTORE = 54;
  public static final int EXTERNAL = 33;
  public static final int SUM = 282;
  public static final int MIN = 299;
  public static final int OUT = 343;
  public static final int TEMPORARY = 286;
  public static final int ABSOLUTE = 211;
  public static final int CONVERT = 118;
  public static final int ORDER = 183;
  public static final int identificador = 7;
  public static final int AbreCorchetes = 25;
  public static final int COMPUTE = 103;
  public static final int Resta = 4;
  public static final int entero = 8;
  public static final int TO = 138;
  public static final int LIKE = 122;
  public static final int FILE = 37;
  public static final int TB = 368;
  public static final int REPLICATION = 51;
  public static final int PRIMARY = 204;
  public static final int MayorIgual = 15;
  public static final int DEFERRABLE = 315;
  public static final int FLOAT = 226;
  public static final int DOUBLE = 177;
  public static final int ARYING = 184;
  public static final int SEMANTICKEYPHRASETABLE = 96;
  public static final int SELECT = 93;
  public static final int VARYING = 331;
  public static final int CHECK = 79;
  public static final int TRIM = 306;
  public static final int FIRST = 224;
  public static final int NAMES = 310;
  public static final int INPUT = 263;
  public static final int SQLSTATE = 276;
  public static final int WHERE = 196;
  public static final int UPDATE = 170;
  public static final int SELF = 351;
  public static final int BETWEEN = 58;
  public static final int flotan = 10;
  public static final int RAISERROR = 38;
  public static final int RECONFIGURE = 46;
  public static final int IDENTITY = 77;
  public static final int GROUP = 68;
  public static final int TRANSLATION = 303;
  public static final int USING = 322;
  public static final int TSEQUAL = 159;
  public static final int PRESERVE = 225;
  public static final int USER = 179;
  public static final int DOMAIN = 332;
  public static final int SQL = 268;
  public static final int LOCAL = 293;
  public static final int TRANSLATE = 300;
  public static final int SYSTEM_USER = 123;
  public static final int SCHEMABINDING = 347;
  public static final int VALUE = 324;
  public static final int ONLY = 334;
  public static final int FAST_FORWARD = 359;
  public static final int EXIT = 209;
  public static final int LEADING = 288;
  public static final int TABLE = 126;
  public static final int SCHEMA = 87;
  public static final int error = 1;
  public static final int REVERT = 63;
  public static final int Igual = 2;
  public static final int WAITFOR = 190;
  public static final int FORTRAN = 231;
  public static final int STATISTICS = 120;
  public static final int NOCHECK = 137;
  public static final int TIME = 289;
  public static final int AbreParentesis = 26;
  public static final int LEFT = 119;
  public static final int OR = 32;
  public static final int ASSERTION = 233;
  public static final int PROC = 210;
  public static final int WHENEVER = 335;
  public static final int ON = 333;
  public static final int CASCADE = 73;
  public static final int EXCEPTION = 342;
  public static final int CHAR = 255;
  public static final int OF = 152;
  public static final int WITHIN_GROUP = 205;
  public static final int ROWGUIDCOL = 78;
  public static final int DELETE = 160;
  public static final int UPPER = 317;
  public static final int ADD = 30;
  public static final int ADA = 215;
  public static final int COMMIT = 100;
  public static final int CLUSTERED = 88;
  public static final int ACTION = 213;
  public static final int JOIN = 110;
  public static final int WHEN = 193;
  public static final int NULL = 146;
  public static final int MINUTE = 302;
  public static final int INNER = 95;
  public static final int DISTRIBUTED = 174;
  public static final int TRAILING = 297;
  public static final int CONTAINSTABLE = 112;
  public static final int TRANSACTION = 147;
  public static final int NO = 319;
  public static final int OPENXML = 175;
  public static final int FUNCTION = 59;
  public static final int PRIOR = 228;
  public static final int SPACE = 266;
  public static final int CAST = 251;
  public static final int OWNER = 352;
  public static final int STATIC = 356;
  public static final int CHAR_LENGTH = 257;
  public static final int SHUTDOWN = 114;
  public static final int NAME = 364;
  public static final int INSENSITIVE = 265;
  public static final int SCROLL = 248;
  public static final int CASE = 76;
  public static final int READ_ONLY = 360;
  public static final int ERRLVL = 191;
  public static final int PLAN = 198;
  public static final int UPDATETEXT = 173;
  public static final int UNION = 161;
  public static final int DROP = 180;
  public static final int MAX = 298;
  public static final int OUTPUT = 340;
  public static final int PyC = 17;
  public static final int PRINT = 207;
  public static final int INDICATOR = 258;
  public static final int FILLFACTOR = 39;
  public static final int MB = 369;
  public static final int GLOBAL = 239;
  public static final int PARTIAL = 216;
  public static final int COLLATION = 269;
  public static final int GOTO = 62;
  public static final int INCLUDE = 254;
  public static final int WHILE = 199;
  public static final int SEMANTICSIMILARITYTABLE = 102;
  public static final int CONNECT = 275;
  public static final int VARCHAR = 328;
  public static final int CURRENT_TIMESTAMP = 136;
  public static final int BULK = 67;
  public static final int INITIALLY = 260;
  public static final int Division = 6;
  public static final int FALSE = 222;
  public static final int SESSION = 256;
  public static final int AUTHORIZATION = 49;
  public static final int EXEC = 200;
  public static final int REFERENCES = 48;
  public static final int Arroba = 20;
  public static final int CREATE = 121;
  public static final int CierraCorchetes = 27;
  public static final int INSERT = 98;
  public static final int CHECKPOINT = 82;
  public static final int REAL = 236;
  public static final int Mayor = 14;
  public static final int ISOLATION = 279;
  public static final int READ = 40;
  public static final int SMALLINT = 264;
  public static final int KB = 366;
  public static final int WITH = 202;
  public static final int CURRENT = 127;
  public static final int CHARACTER = 259;
  public static final int DATE = 301;
  public static final int TRAN = 144;
  public static final int DISK = 168;
  public static final int DESCRIBE = 323;
  public static final int ENCRYPTION = 345;
  public static final int HOLDLOCK = 74;
  public static final int OVER = 189;
  public static final int OUTER = 186;
  public static final int INLINE = 349;
  public static final int DESC = 165;
  public static final int DEC = 309;
  public static final int USAGE = 320;
  public static final int HOUR = 246;
  public static final int FREETEXTTABLE = 50;
  public static final int IS = 107;
  public static final int RETURNS = 346;
  public static final int ROWCOUNT = 75;
  public static final int IN = 89;
  public static final int OVERLAPS = 212;
  public static final int SETUSER = 111;
  public static final int MERGE = 131;
  public static final int Corchetes = 22;
  public static final int CALLER = 350;
  public static final int DISTINCT = 171;
  public static final int IF = 86;
  public static final int CONSTRAINTS = 281;
  public static final int UNKNOWN = 313;
  public static final int RIGHT = 69;
  public static final int CROSS = 124;
  public static final int NOT = 143;
  public static final int YEAR = 339;
  public static final int MATCH = 296;
  public static final int PASCAL = 217;
  public static final int IDENTITYCOL = 83;
  public static final int CALLED = 348;
  public static final int EXCEPT = 197;
  public static final int NATIONAL = 134;
  public static final int READTEXT = 43;
  public static final int DYNAMIC = 358;
  public static final int CHARACTER_LENGTH = 261;
  public static final int COLLATE = 94;
  public static final int FOUND = 234;
  public static final int AVG = 237;
  public static final int FOR = 42;
  public static final int COALESCE = 91;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Igual",
  "Suma",
  "Resta",
  "Multiplicacion",
  "Division",
  "identificador",
  "entero",
  "cadena",
  "flotan",
  "Porcentaje",
  "Menor",
  "MenorIgual",
  "Mayor",
  "MayorIgual",
  "NoIgual",
  "PyC",
  "Coma",
  "Punto",
  "Arroba",
  "Numeral",
  "Corchetes",
  "Llaves",
  "Parentesis",
  "AbreCorchetes",
  "AbreParentesis",
  "CierraCorchetes",
  "CierraParentesis",
  "ERROR",
  "ADD",
  "AND",
  "OR",
  "EXTERNAL",
  "FETCH",
  "PUBLIC",
  "ALTER",
  "FILE",
  "RAISERROR",
  "FILLFACTOR",
  "READ",
  "ANY",
  "FOR",
  "READTEXT",
  "AS",
  "FOREIGN",
  "RECONFIGURE",
  "FREETEXT",
  "REFERENCES",
  "AUTHORIZATION",
  "FREETEXTTABLE",
  "REPLICATION",
  "BACKUP",
  "FROM",
  "RESTORE",
  "BEGIN",
  "FULL",
  "RESTRICT",
  "BETWEEN",
  "FUNCTION",
  "RETURN",
  "BREAK",
  "GOTO",
  "REVERT",
  "BROWSE",
  "GRANT",
  "REVOKE",
  "BULK",
  "GROUP",
  "RIGHT",
  "BY",
  "HAVING",
  "ROLLBACK",
  "CASCADE",
  "HOLDLOCK",
  "ROWCOUNT",
  "CASE",
  "IDENTITY",
  "ROWGUIDCOL",
  "CHECK",
  "IDENTITY_INSERT",
  "RULE",
  "CHECKPOINT",
  "IDENTITYCOL",
  "SAVE",
  "CLOSE",
  "IF",
  "SCHEMA",
  "CLUSTERED",
  "IN",
  "SECURITYAUDIT",
  "COALESCE",
  "INDEX",
  "SELECT",
  "COLLATE",
  "INNER",
  "SEMANTICKEYPHRASETABLE",
  "COLUMN",
  "INSERT",
  "SEMANTICSIMILARITYDETAILSTABLE",
  "COMMIT",
  "INTERSECT",
  "SEMANTICSIMILARITYTABLE",
  "COMPUTE",
  "INTO",
  "SESSION_USER",
  "CONSTRAINT",
  "IS",
  "SET",
  "CONTAINS",
  "JOIN",
  "SETUSER",
  "CONTAINSTABLE",
  "KEY",
  "SHUTDOWN",
  "CONTINUE",
  "KILL",
  "SOME",
  "CONVERT",
  "LEFT",
  "STATISTICS",
  "CREATE",
  "LIKE",
  "SYSTEM_USER",
  "CROSS",
  "LINENO",
  "TABLE",
  "CURRENT",
  "LOAD",
  "TABLESAMPLE",
  "CURRENT_DATE",
  "MERGE",
  "TEXTSIZE",
  "CURRENT_TIME",
  "NATIONAL",
  "THEN",
  "CURRENT_TIMESTAMP",
  "NOCHECK",
  "TO",
  "CURRENT_USER",
  "NONCLUSTERED",
  "TOP",
  "CURSOR",
  "NOT",
  "TRAN",
  "DATABASE",
  "NULL",
  "TRANSACTION",
  "DBCC",
  "NULLIF",
  "TRIGGER",
  "DEALLOCATE",
  "OF",
  "TRUNCATE",
  "DECLARE",
  "OFF",
  "TRY_CONVERT",
  "DEFAULT",
  "OFFSETS",
  "TSEQUAL",
  "DELETE",
  "UNION",
  "DENY",
  "OPEN",
  "UNIQUE",
  "DESC",
  "OPENDATASOURCE",
  "UNPIVOT",
  "DISK",
  "OPENQUERY",
  "UPDATE",
  "DISTINCT",
  "OPENROWSET",
  "UPDATETEXT",
  "DISTRIBUTED",
  "OPENXML",
  "USE",
  "DOUBLE",
  "OPTION",
  "USER",
  "DROP",
  "VALUES",
  "DUMP",
  "ORDER",
  "ARYING",
  "ELSE",
  "OUTER",
  "VIEW",
  "END",
  "OVER",
  "WAITFOR",
  "ERRLVL",
  "PERCENT",
  "WHEN",
  "ESCAPE",
  "PIVOT",
  "WHERE",
  "EXCEPT",
  "PLAN",
  "WHILE",
  "EXEC",
  "PRECISION",
  "WITH",
  "EXECUTE",
  "PRIMARY",
  "WITHIN_GROUP",
  "EXISTS",
  "PRINT",
  "WRITETEXT",
  "EXIT",
  "PROC",
  "ABSOLUTE",
  "OVERLAPS",
  "ACTION",
  "PAD",
  "ADA",
  "PARTIAL",
  "PASCAL",
  "ALL",
  "EXTRACT",
  "POSITION",
  "ALLOCATE",
  "FALSE",
  "PREPARE",
  "FIRST",
  "PRESERVE",
  "FLOAT",
  "ARE",
  "PRIOR",
  "PRIVILEGES",
  "ASC",
  "FORTRAN",
  "PROCEDURE",
  "ASSERTION",
  "FOUND",
  "AT",
  "REAL",
  "AVG",
  "GET",
  "GLOBAL",
  "RELATIVE",
  "GO",
  "BIT",
  "BIT_LENGTH",
  "BOTH",
  "ROWS",
  "HOUR",
  "CASCADED",
  "SCROLL",
  "IMMEDIATE",
  "SECOND",
  "CAST",
  "SECTION",
  "CATALOG",
  "INCLUDE",
  "CHAR",
  "SESSION",
  "CHAR_LENGTH",
  "INDICATOR",
  "CHARACTER",
  "INITIALLY",
  "CHARACTER_LENGTH",
  "SIZE",
  "INPUT",
  "SMALLINT",
  "INSENSITIVE",
  "SPACE",
  "INT",
  "SQL",
  "COLLATION",
  "INTEGER",
  "SQLCA",
  "SQLCODE",
  "INTERVAL",
  "SQLERROR",
  "CONNECT",
  "SQLSTATE",
  "CONNECTION",
  "SQLWARNING",
  "ISOLATION",
  "SUBSTRING",
  "CONSTRAINTS",
  "SUM",
  "LANGUAGE",
  "CORRESPONDING",
  "LAST",
  "TEMPORARY",
  "COUNT",
  "LEADING",
  "TIME",
  "LEVEL",
  "TIMESTAMP",
  "TIMEZONE_HOUR",
  "LOCAL",
  "TIMEZONE_MINUTE",
  "LOWER",
  "MATCH",
  "TRAILING",
  "MAX",
  "MIN",
  "TRANSLATE",
  "DATE",
  "MINUTE",
  "TRANSLATION",
  "DAY",
  "MODULE",
  "TRIM",
  "MONTH",
  "TRUE",
  "DEC",
  "NAMES",
  "DECIMAL",
  "NATURAL",
  "UNKNOWN",
  "NCHAR",
  "DEFERRABLE",
  "NEXT",
  "UPPER",
  "DEFERRED",
  "NO",
  "USAGE",
  "NONE",
  "USING",
  "DESCRIBE",
  "VALUE",
  "DESCRIPTOR",
  "DIAGNOSTICS",
  "NUMERIC",
  "VARCHAR",
  "DISCONNECT",
  "OCTET_LENGTH",
  "VARYING",
  "DOMAIN",
  "ON",
  "ONLY",
  "WHENEVER",
  "WORK",
  "END_EXEC",
  "WRITE",
  "YEAR",
  "OUTPUT",
  "ZONE",
  "EXCEPTION",
  "OUT",
  "READONLY",
  "ENCRYPTION",
  "RETURNS",
  "SCHEMABINDING",
  "CALLED",
  "INLINE",
  "CALLER",
  "SELF",
  "OWNER",
  "RECOMPILE",
  "MARK",
  "FORWARD_ONLY",
  "STATIC",
  "KEYSET",
  "DYNAMIC",
  "FAST_FORWARD",
  "READ_ONLY",
  "SCROLL_LOCKS",
  "OPTIMISTIC",
  "TYPE_WARNING",
  "NAME",
  "FILENAME",
  "KB",
  "GB",
  "TB",
  "MB",
  "MAXSIZE",
  "UNLIMITED",
  "FILEGROWTH",
  "MODULAR"
  };
}

